name: WoolGens
version: '1.0-SNAPSHOT'
main: its.fire.woolGens.WoolGens
api-version: '1.21'
authors: [ ItsFire ]
description: This is the WoolGens plugin.
commands:
  vanish:
    description: Toggles your visibility!
    usage: /vanish
  fly:
    description: Toggles flight!
    usage: /fly
  getwhitedye:
    description: gives you a white dye!
    usage: /getwhitedye
  getorangedye:
    description: gives you a orange dye!
    usage: /getorangedye
  getmagentadye:
    description: gives you a magenta dye!
    usage: /getmagentadye
  sell:
    description: WIP!
    usage: /sell
  sb:
    description: shows scoreboard!
    usage: /sb